;;; meta-tool.el --- Self-authoring tools for the gptel agent -*- lexical-binding: t; -*-

;; `define_tool' lets the model write a brand-new Elisp tool, load it
;; into the running session immediately, and have it persist across
;; restarts (core/init.el reloads everything under
;; `gptel-agent-tools-dir' on startup).
;;
;; The model supplies only a function body and an :args spec as Lisp
;; source strings; this file generates the surrounding
;; `gptel-make-tool' boilerplate from a fixed template, and
;; syntax-checks both before anything is written to disk or loaded.
;; Existing tool files require overwrite=true to replace. Generated
;; tools default to :confirm t unless the model passes confirm=false.

(require 'gptel)
(defvar gptel-agent-tools-dir) ; defined in init.el, loaded before this file
(declare-function gptel-agent--bool "tools-read")
(declare-function gptel-agent--tools-set "tools-read")

(defvar gptel-agent-meta-tools nil
  "Tool structs registered by this file. Enabled by default in
`gptel-tools' -- see `gptel-agent-disable-meta-tools' to opt out
per-buffer, and `gptel-agent-enable-meta-tools' to opt back in. Kept
as a separate on/off switch from `gptel-agent-write-tools' since
self-authoring code is a meaningfully higher trust bar than editing a
buffer or file.")

(defun gptel-agent--register-meta-tool (&rest args)
  "Register a meta tool via `gptel-make-tool', confirm-gated, and
added to the default `gptel-tools' list."
  (let ((tool (apply #'gptel-make-tool (append args (list :confirm t)))))
    (gptel-agent--tools-set 'gptel-agent-meta-tools tool)
    tool))

;;;###autoload
(defun gptel-agent-enable-meta-tools ()
  "(Re-)enable gptel's self-authoring tool (define_tool) in the
current buffer. Enabled by default; use this to turn it back on after
`gptel-agent-disable-meta-tools'."
  (interactive)
  (setq-local gptel-tools (append gptel-agent-meta-tools
                                   (seq-difference gptel-tools gptel-agent-meta-tools)))
  (message "gptel-agent: meta tools enabled in %s" (buffer-name)))

;;;###autoload
(defun gptel-agent-disable-meta-tools ()
  "Remove gptel's self-authoring tool (define_tool) from the current
buffer's tool list, if you don't want the model creating new tools in
this conversation. Use `gptel-agent-enable-meta-tools' to turn it back on."
  (interactive)
  (setq-local gptel-tools (seq-difference gptel-tools gptel-agent-meta-tools))
  (message "gptel-agent: meta tools disabled in %s" (buffer-name)))

;; --- define_tool -----------------------------------------------------

(defun gptel-agent--valid-tool-name-p (name)
  "Non-nil if NAME is safe to use as both a file name component and a
tool/category identifier: snake_case-ish, no path separators, no
leading digit."
  (and (stringp name)
       (string-match-p "\\`[a-zA-Z_][a-zA-Z0-9_]*\\'" name)))

(defun gptel-agent--read-lisp-form (source what)
  "Parse SOURCE (a string) as a single Lisp form. Returns (form . nil)
on success, or (nil . error-message) on failure. WHAT names the field
being parsed, for the error message. Never signals -- always returns a
result the caller can act on."
  (condition-case err
      (let ((form (car (read-from-string source))))
        (cons form nil))
    (error (cons nil (format "Could not parse %s as Lisp: %s" what err)))))

(defun gptel-agent--generate-tool-file (tool-name description function-form args-form confirm category)
  "Return the full text of a generated tool file for TOOL-NAME."
  (format
   ";;; %1$s.el --- Self-authored gptel tool -*- lexical-binding: t; -*-

;; Generated by gptel's define_tool meta-tool on %2$s.
;; Description: %3$s
;;
;; This file was written by the model itself, not by hand. Review it
;; like any other change before trusting it -- `git diff' in
;; ~/.config/gptel/tools/ shows exactly this.

(require 'gptel)

(gptel-make-tool
 :name \"%1$s\"
 :function %4$s
 :description %5$S
 :args %6$s
 :confirm %7$s
 :category %8$S)

(provide 'gptel-agent-tool-%1$s)
;;; %1$s.el ends here
"
   tool-name
   (format-time-string "%Y-%m-%d %H:%M:%S")
   description
   (pp-to-string function-form)
   description
   (pp-to-string args-form)
   (if confirm "t" "nil")
   category))

(defun gptel-agent--define-tool-impl (tool_name description function_elisp args_elisp confirm overwrite)
  "Implementation of the define_tool tool; see its :description for
the user-facing contract. CONFIRM and OVERWRITE must already be
coerced to proper Elisp booleans (see `gptel-agent--bool')
before calling this."
  (if (not (gptel-agent--valid-tool-name-p tool_name))
      (format "Invalid tool_name %S -- must look like a snake_case identifier (letters, digits, underscore, not starting with a digit), no slashes or dots."
              tool_name)
    (let* ((path (expand-file-name (concat tool_name ".el") gptel-agent-tools-dir))
           (function-parse (gptel-agent--read-lisp-form function_elisp "function_elisp"))
           (args-parse (gptel-agent--read-lisp-form (or args_elisp "nil") "args_elisp")))
      (cond
       ((and (file-exists-p path) (not overwrite))
        (format "Tool '%s' already exists at %s. Pass overwrite=true to redefine it."
                tool_name path))
       ((cdr function-parse) (cdr function-parse))
       ((cdr args-parse) (cdr args-parse))
       (t
        (let ((content (gptel-agent--generate-tool-file
                        tool_name description (car function-parse) (car args-parse)
                        confirm "self-authored")))
          (with-temp-file path (insert content))
          (condition-case err
              (progn
                (load path)
                (format "Tool '%s' created at %s and loaded into this session. It will also auto-load on future Emacs restarts. It defaults to confirm=%s when called."
                        tool_name path confirm))
            (error
             (format "Wrote %s but failed to load it: %s. The file is still on disk for you to inspect/fix/delete; it will NOT auto-load until it loads successfully."
                     path err)))))))))

(gptel-agent--register-meta-tool
 :name "define_tool"
 :function
 (lambda (tool_name description function_elisp args_elisp &optional confirm overwrite)
   (gptel-agent--define-tool-impl
    tool_name description function_elisp args_elisp
    (not (eq confirm :json-false))  ; explicit false -> nil; omitted/true -> t
    (gptel-agent--bool overwrite)))
 :description "Write a brand-new Emacs Lisp tool for yourself and load
it into the current session immediately, so it becomes available for
future tool calls (including later in this same conversation, once
accepted). The tool persists across Emacs restarts.

Do NOT write a full `gptel-make-tool' call yourself -- supply only:
- function_elisp: the source of a `lambda' expression implementing the
  tool, e.g. \"(lambda (path) (if (file-exists-p path) \\\"yes\\\" \\\"no\\\"))\".
  It should return a short, plain-English/string result and should
  avoid signaling errors -- catch failure cases and return a message
  describing them instead.
- args_elisp: the source of the :args list gptel expects, e.g.
  \"(list '(:name \\\"path\\\" :type string :description \\\"A file path\\\"))\",
  or \"nil\" for a tool that takes no arguments.
This wrapper generates the surrounding `gptel-make-tool' registration
for you from a fixed template, so the result is consistent regardless
of what you pass.

By default the new tool itself will require user confirmation before
each call (safe default for anything that isn't obviously read-only) --
pass confirm=false only for tools you're confident are read-only/safe.

If a tool with this name already exists, you must pass overwrite=true
to replace it."
 :args (list '(:name "tool_name" :type string
               :description "snake_case name for the new tool, e.g. \"count_todos\"")
             '(:name "description" :type string
               :description "Description shown to the LLM for when/how to use this tool")
             '(:name "function_elisp" :type string
               :description "Source text of a (lambda (...) ...) form implementing the tool")
             '(:name "args_elisp" :type string
               :description "Source text of the gptel :args list (a `(list '(:name ...) ...)` form), or \"nil\" for no arguments")
             '(:name "confirm" :type boolean :optional t
               :description "Whether the new tool itself should require confirmation before each call. Defaults to true (safer) if omitted.")
             '(:name "overwrite" :type boolean :optional t
               :description "Required to be true if a tool with this name already exists"))
 :category "meta")

(provide 'gptel-agent-meta-tool)
;;; meta-tool.el ends here
